# Generated by Django 5.1.7 on 2025-03-23 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loading_city_primary', models.CharField(max_length=255)),
                ('loading_postal_primary', models.CharField(blank=True, max_length=20, null=True)),
                ('loading_city_secondary', models.CharField(blank=True, max_length=255, null=True)),
                ('loading_postal_secondary', models.CharField(blank=True, max_length=20, null=True)),
                ('unloading_city_primary', models.CharField(max_length=255)),
                ('unloading_postal_primary', models.CharField(blank=True, max_length=20, null=True)),
                ('unloading_city_secondary', models.CharField(blank=True, max_length=255, null=True)),
                ('unloading_postal_secondary', models.CharField(blank=True, max_length=20, null=True)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField(blank=True, null=True)),
                ('cargo_type', models.CharField(max_length=255)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transport_type', models.IntegerField(default=0)),
                ('truck_count', models.IntegerField(default=1)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('price_per_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('humanitarian_aid', models.BooleanField(default=False)),
                ('extra_info', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
