# Generated by Django 5.1.7 on 2025-03-29 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_cargo_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loading_date_from', models.DateField()),
                ('loading_date_to', models.DateField()),
                ('loading_location', models.CharField(max_length=255)),
                ('additional_loading_location', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('number_of_vehicles', models.PositiveIntegerField(default=1)),
                ('unloading_location', models.CharField(max_length=255)),
                ('additional_unloading_location', models.CharField(blank=True, max_length=255, null=True)),
                ('carrying_capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('useful_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('skype', models.CharField(blank=True, max_length=100, null=True)),
                ('viber', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=50, null=True)),
                ('has_gps', models.BooleanField(default=False)),
                ('is_humanitarian', models.BooleanField(default=False)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
