# Generated by Django 5.1.7 on 2025-03-30 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_truck_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='transport_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='carrying_capacity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='number_of_vehicles',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='truck',
            name='useful_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='viber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
