# Generated by Django 5.1.7 on 2025-04-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_profile_delete_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='language',
            new_name='mobile',
        ),
        migrations.AddField(
            model_name='profile',
            name='client_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_language',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
