# Generated by Django 5.1.7 on 2025-04-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_language_profile_mobile_profile_client_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='loading_canton',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='unloading_canton',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='viber_whatsapp_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
