# Generated by Django 5.1.7 on 2025-04-05 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_cargo_loading_canton_cargo_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='loading_canton',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='loading_city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='unloading_canton',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='unloading_city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
