# Generated by Django 5.1.7 on 2025-04-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_truck_loading_canton_truck_loading_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='email',
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='email',
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
    ]
