# Generated by Django 5.1.7 on 2025-04-05 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_cargo_email_alter_truck_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='additional_unloading_location',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='is_humanitarian',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='skype',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='unloading_location',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='viber',
        ),
    ]
