# Generated by Django 5.1.7 on 2025-04-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_truck_additional_unloading_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='loading_postal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='unloading_postal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
