# Generated by Django 5.1.7 on 2025-04-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_truck_loading_postal_truck_unloading_postal'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
