# Generated by Django 5.1.7 on 2025-04-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_truck_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo',
            old_name='unloading_postal_secondary',
            new_name='cargo_loading_street',
        ),
        migrations.AddField(
            model_name='cargo',
            name='cargo_unloading_street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='truck_loading_street',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='truck_unloading_street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
