# Generated by Django 5.1.7 on 2025-04-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_unloading_postal_secondary_cargo_cargo_loading_street_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
