# Generated by Django 5.1.7 on 2025-04-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_companydocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydocument',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
