# Generated by Django 5.1.7 on 2025-04-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_companydocument_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydocument',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
