# Generated by Django 5.1.7 on 2025-04-23 16:44

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_companydocument_is_rejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydocument',
            name='file',
            field=models.FileField(upload_to=api.models.user_directory_path),
        ),
    ]
